### ISSUE TITLE
SpringBoot 설정파일 local, dev, prd에 따라 나누기

### ISSUE THREAD

**Issue by choi3179** [T2-Papillon/Spring#12]
### application.yml 개발환경 구성
- https://github.com/T2-Papillon/Spring/pull/11
- 개발환경에 따라 설정파일이 다르게 적용할 수 있도록(ex.DB 연결) 변경해 봤습니다.
- 기본은 application-local.yml 설정이 적용됩니다.
- [ ] dev, prd는 배포 시에 DB 관련 내용이 설정파일에 있으면 보안상 안 좋다고 해서 추후에 변경해 볼 예정입니다.

**Comment by choi3179** [comment]
### 기본 설정
```yaml
# 환경변수에 따라 .jar 파일에 다른 yml 파일이 적용되게 만든다.
# local, dev, prd
# java -jar papplan-0.0.1-SNAPSHOT.jar --spring.profiles.active=prd

# 기본값은 local 프로필으로 설정
spring:
  profiles:
    default: local
  application:
    name: papplan
---
spring:
  config:
    activate:
      on-profile: local, dev, prd
```

**Comment by choi3179** [comment]
### application-local.yml
```yaml
spring:
  sql:
    init:
      platform: mariadb
      encoding: UTF-8
      mode: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # local DB URL 설정
    url: jdbc:mariadb://localhost:3307/papplan
    username: [계정]
    password: [비밀번호]
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true

# Hibernate SQL ?? ?? ??
logging:
  level:
    org:
      hibernate:
        SQL: debug
```

**Comment by choi3179** [comment]
### application-dev.yml
```yaml
spring:
  sql:
    init:
      platform: mariadb
      encoding: UTF-8
      mode: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://[개발 DB URL]/papplan
    username: [계정]
    password: [비밀번호]
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false

# Hibernate SQL ?? ?? ??
logging:
  level:
    org:
      hibernate:
        SQL: debug
```
